movieproject/movieapp/urls.py
from django.urls import path
from . import views

app_name = 'movieapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('movie/<int:movie_id>/', views.detail, name='detail'),
    path('add/', views.add_movie, name='add_movie'),
    path('update/<int:id>/', views.update, name='update'),
    path('delete/<int:id>/', views.delete, name='delete'),
]

movieproject/movieproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movieapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movieproject/movieapp/models.py
from django.db import models


# Create your models here.
class Movie(models.Model):
    name = models.CharField(max_length=250)
    desc = models.TextField()
    year = models.IntegerField()
    img = models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

movieproject/movieapp/forms.py
from django import forms
from .models import Movie


class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ['name', 'desc', 'year', 'img']

movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Movie
from .forms import MovieForm


# Create your views here.
def index(request):
    movie = Movie.objects.all()
    context = {
        'movie_list': movie
    }

    return render(request, 'index.html', context)


def detail(request, movie_id):
    movie = Movie.objects.get(id=movie_id)
    return render(request, "detail.html", {'movie': movie})


def add_movie(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        desc = request.POST.get('desc')
        year = request.POST.get('year')
        img = request.FILES['img']
        movie = Movie(name=name, desc=desc, year=year, img=img)
        movie.save()

    return render(request, 'add.html')


def update(request, id):
    movie = Movie.objects.get(id=id)
    form = MovieForm(request.POST or None, request.FILES, instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, 'edit.html', {'form': form, 'movie': movie})


def delete(request, id):
    if request.method == 'POST':
        movie = Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request, 'delete.html')

movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<centre>
<form method="POST" enctype="multipart/form-data" align="center">
  {% csrf_token %}
  <h1>ONLINE MOVIE STORE</h1>
  <br><br>
  <input type="text" name="name" placeholder="Enter your Movie Name"><br><br>
  <input type="text" name="desc" placeholder="Enter the movie description"><br><br>
  <input type="text" name="year" placeholder="Enter the Year of Movie"><br><br>
  <input type="file" name="img"><br><br><br>
  <input type="submit"><br>
</form>
</centre>

{% endblock %}

movieproject/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Just an image -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    Online Movie Store
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

movieproject/templates/delete.html
<html>
<body bgcolor="Gray">
<form method="POST" align="center">
    {% csrf_token %}
    <br><br>
    <h2>Are you sure you want to delete the selected movie?</h2><br>
    <input type="submit" style="color:red;font-size:25px">
</form>
</body>
</html>

movieproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}
    <div class="row">
        <div class="col-md-4">
            <img src="{{movie.img.url}}" width="300" height="300">
        </div>
            <div class="col-md-6">
            <u><h2 style="color:blue" align="center">{{movie.name}}<br><br></h2></u>
            <h5 align="left">{{movie.desc}}<br><br></h5>
            <h6>Movie Year:{{movie.year}}</h6><br><br>
            <a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}">UPDATE</a>
            <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">DELETE</a>
        </div>
    </div>
        <br><br>
{% endblock %}

movieproject/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Update</title>
</head>
<body bgcolor="DarkSeaGreen">
<u><h1 style="color:Purple" align="center">Update Your Fields</h1></u><br>
<form method="POST" enctype="multipart/form-data" align="center">
    {% csrf_token %}
    {{form.as_p}}
    <br>
    <h1><input type="submit" style="color:red;font-size:25px"></h1>
</form>
</body>
</html>

movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        {% for i in movie_list %}
         <div class="col-md-4">
            <div class="card" style="width: 18rem;">
                <img src="{{i.img.url}}" width="285px" height="250px" class="Card-img-top" alt="..." sizes="200px">
                <div class="card-body">
                  <h5 class="card-title">{{i.name}}</h5>
                    <p class="card-text">{{i.desc}}</p>
                        <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">View More...</a>
                </div>
           </div>
        </div>
        {% endfor %}
  </div>
</div>

{% endblock %}